
POST http://localhost:3000/Api/V4/ItemsTable/Insert
Content-Type: application/json

{
  "StockItemName": "",
  "Rate": "",
  "Qty": "",
  "Amount": "",
  "TaxPer": "",
  "Uom": "",
  "ParentPk": ""
}
