
POST http://localhost:3000/Api/V4/BillsTable/Insert
Content-Type: application/json

{
  "LedgerName": "",
  "LedgerParentName": "",
  "LedgerGST": "",
  "InvoiceNo": "",
  "InvoiceDate": "",
  "InvoiceStateCode": ""
}
